import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { Flight } from '../flight';
import { BookingDetails } from '../booking-details';
import { BookingService } from '../booking-service';


@Component({
  selector: 'app-booking-list',
  imports: [FormsModule, CommonModule],
  templateUrl: './booking-list.html',
  styleUrls: ['./booking-list.css']
})
export class BookingList implements OnInit {
  // View state - which screen to show
  currentView: 'results' | 'booking' | 'payment' = 'results';
  
  // Search criteria (from previous screen)
  source: string = '';
  destination: string = '';
  departureDate: string = '';
  
  // Selected flight and booking details
  selectedFlight: Flight | null = null;
  errorMessage: string = '';
  showBookingSuccess: boolean = false;
  bookingId: string = ''; // Generated by backend
  
  // Payment details
  paymentMethod: 'card' | 'upi' = 'card';
  cardNumber: string = '';
  expiryDate: string = '';
  cvv: string = '';
  cardHolderName: string = '';
  upiId: string = '';
  paymentProcessing: boolean = false;
  paymentStatus: 'pending' | 'success' | 'failed' = 'pending';

  // Passenger details
  bookingDetails: BookingDetails = {
    passengerName: '',
    passengerEmail: '',
    passengerPhone: ''
  };

  // Flights data
  flights: Flight[] = [];
  allFlights: Flight[] = [];
  appliedFilters: { label: string, value: string }[] = [];
  
  // Filter states
  nonStopFilter = false;
  indigoFilter = false;
  morningFilter = false;
  eveningFilter = false;
  airIndiaFilter = false;

  constructor(
    private router: Router,
    private bookingService: BookingService,   // ← NEW: Inject BookingService
    private cdr: ChangeDetectorRef            // ← NEW: For manual change detection
  ) {
    // Get data passed from FlightSearch component
    const navigation = this.router.getCurrentNavigation();
    if (navigation?.extras.state) {
      this.source = navigation.extras.state['source'] || '';
      this.destination = navigation.extras.state['destination'] || '';
      this.departureDate = navigation.extras.state['departureDate'] || '';
      
      // Get flights from backend (passed via navigation)
      const backendFlights = navigation.extras.state['flights'];
      if (backendFlights && backendFlights.length > 0) {
        console.log('Converting backend flights to frontend format...');
        this.allFlights = this.convertBackendFlights(backendFlights);
        this.flights = [...this.allFlights];
        console.log('Flights loaded:', this.flights.length);
      }
    }
  }

  ngOnInit(): void {
    // Data already loaded in constructor
  }

  
  private convertBackendFlights(backendFlights: any[]): Flight[] {
    return backendFlights.map(bf => ({
      id: bf.flightId,
      flightNumber: bf.flightNumber,
      airline: bf.airline,
      source: bf.source,
      destination: bf.destination,
      departureTime: bf.departureTime,
      arrivalTime: bf.arrivalTime,
      price: bf.price.toString(),
      duration: bf.duration,
      stopType: bf.stopType,
      isNonStop: bf.isNonStop || bf.stopType === 'Non-stop',
      isMorning: bf.isMorning,
      isLate: bf.isLate,
      departureHour: bf.departureHour
    }));
  }

  goToSearch(): void {
    this.router.navigate(['/flightsearch']);
  }

  
  
  getMinPrice(filterType: string): number {
    let filtered: Flight[] = [];
    
    switch(filterType) {
      case 'nonStop':
        filtered = this.allFlights.filter(f => f.isNonStop);
        break;
      case 'IndiGo':
        filtered = this.allFlights.filter(f => f.airline === 'IndiGo');
        break;
      case 'morning':
        filtered = this.allFlights.filter(f => f.isMorning);
        break;
      case 'evening':
        filtered = this.allFlights.filter(f => f.departureHour >= 17);
        break;
      case 'airIndia':
        filtered = this.allFlights.filter(f => f.airline === 'Air India');
        break;
    }
    
    return filtered.length > 0 ? Math.min(...filtered.map(f => Number(f.price))) : 0;
  }

  toggleNonStopFilter(): void { 
    this.nonStopFilter = !this.nonStopFilter; 
    this.updateFlights(); 
    this.updateAppliedFilters(); 
  }
  
  toggleIndigoFilter(): void { 
    this.indigoFilter = !this.indigoFilter; 
    this.updateFlights(); 
    this.updateAppliedFilters(); 
  }
  
  toggleMorningFilter(): void { 
    this.morningFilter = !this.morningFilter; 
    this.updateFlights(); 
    this.updateAppliedFilters(); 
  }

  toggleEveningFilter(): void { 
    this.eveningFilter = !this.eveningFilter; 
    this.updateFlights(); 
    this.updateAppliedFilters(); 
  }

  toggleAirIndiaFilter(): void { 
    this.airIndiaFilter = !this.airIndiaFilter; 
    this.updateFlights(); 
    this.updateAppliedFilters(); 
  }

  removeAppliedFilter(filterValue: string): void {
    switch(filterValue) {
      case 'nonStop':
        this.nonStopFilter = false;
        break;
      case 'IndiGo':
        this.indigoFilter = false;
        break;
      case 'morning':
        this.morningFilter = false;
        break;
      case 'evening':
        this.eveningFilter = false;
        break;
      case 'airIndia':
        this.airIndiaFilter = false;
        break;
    }
    this.updateFlights(); 
    this.updateAppliedFilters();
  }

  clearAllFilters(): void { 
    this.nonStopFilter = false;
    this.indigoFilter = false; 
    this.morningFilter = false;
    this.eveningFilter = false;
    this.airIndiaFilter = false;
    this.updateFlights(); 
    this.updateAppliedFilters(); 
  }

  updateFlights(): void {
    let result = [...this.allFlights];
    
    if (this.nonStopFilter) result = result.filter(f => f.isNonStop);
    if (this.indigoFilter) result = result.filter(f => f.airline === 'IndiGo');
    if (this.morningFilter) result = result.filter(f => f.isMorning);
    if (this.eveningFilter) result = result.filter(f => f.departureHour >= 17);
    if (this.airIndiaFilter) result = result.filter(f => f.airline === 'Air India');
    
    this.flights = result;
  }

  updateAppliedFilters(): void {
    this.appliedFilters = [];
    if (this.nonStopFilter) this.appliedFilters.push({ label: 'Non Stop', value: 'nonStop' });
    if (this.indigoFilter) this.appliedFilters.push({ label: 'IndiGo', value: 'IndiGo' });
    if (this.morningFilter) this.appliedFilters.push({ label: 'Morning Departures', value: 'morning' });
    if (this.eveningFilter) this.appliedFilters.push({ label: 'Evening Departures', value: 'evening' });
    if (this.airIndiaFilter) this.appliedFilters.push({ label: 'Air India', value: 'airIndia' });
  }

 
  selectFlight(flight: Flight): void { 
    this.selectedFlight = flight; 
    this.currentView = 'booking'; 
  }


  proceedToPayment(): void {
    // Validate all fields filled
    if (!this.bookingDetails.passengerName || 
        !this.bookingDetails.passengerEmail || 
        !this.bookingDetails.passengerPhone) {
      this.errorMessage = 'Please fill in all passenger details.';
      return;
    }

    // Validate email format
    const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailPattern.test(this.bookingDetails.passengerEmail)) {
      this.errorMessage = 'Please enter a valid email address.';
      return;
    }

    // Validate phone number (10 digits)
    const phone = this.bookingDetails.passengerPhone.replace(/\s/g, '');
    if (!phone.match(/^\d{10}$/)) {
      this.errorMessage = 'Please enter a valid 10-digit phone number.';
      return;
    }

    this.errorMessage = '';

    // Prepare booking data for backend
    const bookingData = {
      flightId: this.selectedFlight?.id,
      source: this.selectedFlight?.source,
      destination: this.selectedFlight?.destination,
      travelDate: this.departureDate,
      passengerName: this.bookingDetails.passengerName,
      passengerEmail: this.bookingDetails.passengerEmail,
      passengerPhone: this.bookingDetails.passengerPhone,
      basePrice: this.getFlightPrice(),
      taxes: this.getTaxesAndFees(),
      totalAmount: this.getTotalAmount()
    };

    console.log('========================================');
    console.log('Creating booking in backend...');
    console.log('Booking data:', bookingData);
    console.log('========================================');

    // Call backend to create booking
    this.bookingService.createBooking(bookingData).subscribe({
      next: (response) => {
        console.log('✅ Booking created successfully!');
        console.log('Booking ID:', response.bookingId);
        console.log('Status:', response.status);
        
        this.bookingId = response.bookingId;
        this.currentView = 'payment';
        this.cdr.detectChanges(); // Trigger UI update
      },
      error: (error) => {
        console.error('❌ Error creating booking:', error);
        this.errorMessage = 'Failed to create booking. Please try again.';
        this.cdr.detectChanges();
      }
    });
  }

  
  processPayment(): void {
    if (!this.validatePaymentDetails()) {
      return;
    }

    this.errorMessage = '';
    this.paymentProcessing = true;

    // Prepare payment data
    const paymentData = {
      bookingId: this.bookingId,
      amount: this.getTotalAmount(),
      paymentMethod: this.paymentMethod,
      cardNumber: this.paymentMethod === 'card' ? this.cardNumber.replace(/\s/g, '') : null,
      expiryDate: this.paymentMethod === 'card' ? this.expiryDate : null,
      cvv: this.paymentMethod === 'card' ? this.cvv : null,
      upiId: this.paymentMethod === 'upi' ? this.upiId : null
    };

    console.log('========================================');
    console.log('Initiating payment via Kafka...');
    console.log('Booking ID:', this.bookingId);
    console.log('Amount:', paymentData.amount);
    console.log('Payment Method:', this.paymentMethod);
    console.log('========================================');

    // Call backend to initiate payment
    this.bookingService.initiatePayment(paymentData).subscribe({
      next: (response) => {
        console.log('✅ Payment request sent to Kafka');
        console.log('Response:', response);
        
        // Start polling for payment status
        // Payment processing happens asynchronously via Kafka
        this.pollPaymentStatus();
      },
      error: (error) => {
        console.error('❌ Error initiating payment:', error);
        this.paymentProcessing = false;
        this.errorMessage = 'Failed to initiate payment. Please try again.';
        this.cdr.detectChanges();
      }
    });
  }

  
  private pollPaymentStatus(): void {
    console.log('========================================');
    console.log('Starting payment status polling...');
    console.log('Will check every 2 seconds');
    console.log('========================================');
    
    this.bookingService.pollBookingStatus(this.bookingId, (booking) => {
      if (!booking) {
        console.error('❌ Failed to get booking status');
        this.paymentProcessing = false;
        this.errorMessage = 'Error checking payment status. Please check your booking later.';
        this.cdr.detectChanges();
        return;
      }

      console.log('========================================');
      console.log('Final Payment Status:', booking.status);
      console.log('========================================');
      
      this.paymentProcessing = false;
      
      if (booking.status === 'SUCCESS') {
        // Payment successful!
        this.paymentStatus = 'success';
        this.showBookingSuccess = true;
        console.log('🎉 Payment successful! Booking confirmed.');
      } else if (booking.status === 'FAILED') {
        // Payment failed
        this.paymentStatus = 'failed';
        console.log('❌ Payment failed.');
      } else {
        // Still INITIATED after max attempts
        this.errorMessage = 'Payment is being processed. Please check your booking status later using Booking ID: ' + this.bookingId;
        console.log('⏳ Payment still processing after timeout.');
      }
      
      this.cdr.detectChanges(); // Update UI
    });
  }

  // ========== PAYMENT VALIDATION ==========

  
  validatePaymentDetails(): boolean {
    if (this.paymentMethod === 'card') {
      return this.validateCardPayment();
    } else if (this.paymentMethod === 'upi') {
      return this.validateUpiPayment();
    }
    return false;
  }

  
  private validateCardPayment(): boolean {
    // Validate card number (16 digits)
    const cardNum = this.cardNumber.replace(/\s/g, '');
    if (!/^\d{16}$/.test(cardNum)) {
      this.errorMessage = 'Card number must be 16 digits.';
      return false;
    }

    // Validate expiry date (MM/YY format)
    if (!/^\d{2}\/\d{2}$/.test(this.expiryDate)) {
      this.errorMessage = 'Please enter expiry date in MM/YY format.';
      return false;
    }

    // Check if expiry date is in future
    const [month, year] = this.expiryDate.split('/');
    const expiryDate = new Date(2000 + parseInt(year), parseInt(month) - 1);
    const today = new Date();
    
    if (expiryDate <= today) {
      this.errorMessage = 'Expiry date should be later than today.';
      return false;
    }

    // Validate CVV (3 digits)
    if (!/^\d{3}$/.test(this.cvv)) {
      this.errorMessage = 'CVV must be 3 digits.';
      return false;
    }

    // Validate card holder name
    if (!this.cardHolderName.trim()) {
      this.errorMessage = 'Please enter card holder name.';
      return false;
    }

    return true;
  }

  
  private validateUpiPayment(): boolean {
    const upiPattern = /^[a-zA-Z0-9.\-_]{2,256}@[a-zA-Z]{2,64}$/;
    if (!upiPattern.test(this.upiId)) {
      this.errorMessage = 'Please enter a valid UPI ID (e.g., username@paytm).';
      return false;
    }
    return true;
  }

  // ========== FORMATTING HELPERS ==========


  formatCardNumber(value: string): void {
    const numericValue = value.replace(/\D/g, '');
    const formattedValue = numericValue.replace(/(\d{4})(?=\d)/g, '$1 ');
    this.cardNumber = formattedValue;
  }

  
  formatExpiryDate(value: string): void {
    const numericValue = value.replace(/\D/g, '');
    if (numericValue.length >= 2) {
      this.expiryDate = numericValue.substring(0, 2) + '/' + numericValue.substring(2, 4);
    } else {
      this.expiryDate = numericValue;
    }
  }

 
  onCardNumberInput(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.formatCardNumber(target.value);
  }

  
  onExpiryDateInput(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.formatExpiryDate(target.value);
  }

  // ========== PRICE CALCULATION HELPERS ==========

  
  getFlightPrice(): number {
    return this.selectedFlight ? Number(this.selectedFlight.price) : 0;
  }

  
  getTaxesAndFees(): number {
    return Math.round(this.getFlightPrice() * 0.12);
  }

  
  getTotalAmount(): number {
    return this.getFlightPrice() + this.getTaxesAndFees();
  }

  // ========== TICKET DOWNLOAD ==========

  
  downloadTicket(): void {
    const ticketContent = this.generateTicketContent();
    
    // Create blob and download
    const blob = new Blob([ticketContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `flight-ticket-${this.bookingId}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
    
    console.log('✅ Ticket downloaded:', `flight-ticket-${this.bookingId}.txt`);
  }

  
  private generateTicketContent(): string {
    return `
==============================================================
                        FLIGHT E-TICKET                       
==============================================================

BOOKING INFORMATION
--------------------------------------------------------------
Booking ID:        ${this.bookingId}
Booking Date:      ${new Date().toLocaleDateString()}
Status:            CONFIRMED

FLIGHT DETAILS
--------------------------------------------------------------
Flight Number:     ${this.selectedFlight?.flightNumber || 'N/A'}
Airline:           ${this.selectedFlight?.airline || 'N/A'}
Route:             ${this.selectedFlight?.source} → ${this.selectedFlight?.destination}
Travel Date:       ${this.departureDate}
Departure Time:    ${this.selectedFlight?.departureTime || 'N/A'}
Arrival Time:      ${this.selectedFlight?.arrivalTime || 'N/A'}
Flight Duration:   ${this.selectedFlight?.duration || 'N/A'}
Flight Type:       ${this.selectedFlight?.stopType || 'N/A'}

PASSENGER DETAILS
--------------------------------------------------------------
Full Name:         ${this.bookingDetails.passengerName}
Email Address:     ${this.bookingDetails.passengerEmail}
Phone Number:      ${this.bookingDetails.passengerPhone}

PAYMENT SUMMARY
--------------------------------------------------------------
Base Fare:         ₹${this.getFlightPrice()}
Taxes & Fees:      ₹${this.getTaxesAndFees()}
--------------------------------------------------------------
TOTAL AMOUNT:      ₹${this.getTotalAmount()}
Payment Method:    ${this.paymentMethod.toUpperCase()}
Payment Status:    SUCCESSFUL

IMPORTANT TRAVEL INFORMATION
--------------------------------------------------------------
- Report at airport 2 hours before domestic departure
- Carry valid government-issued photo identification
- Check baggage allowance limits with airline
- Web check-in available 24 hours before departure
- This is your electronic ticket - print not mandatory
- Keep this ticket for your records

CONTACT INFORMATION
--------------------------------------------------------------
For support and queries:
Email: support@flightbooking.com
Phone: 1800-123-4567
Website: www.flightbooking.com

==============================================================
Thank you for choosing our flight booking service!
Ticket generated on: ${new Date().toLocaleString()}
==============================================================
    `.trim();
  }

  
  startNewBooking(): void {
    // Reset all form data
    this.source = '';
    this.destination = '';
    this.departureDate = '';
    this.selectedFlight = null;
    this.bookingDetails = {
      passengerName: '',
      passengerEmail: '',
      passengerPhone: ''
    };
    this.cardNumber = '';
    this.expiryDate = '';
    this.cvv = '';
    this.cardHolderName = '';
    this.upiId = '';
    this.paymentStatus = 'pending';
    this.showBookingSuccess = false;
    this.errorMessage = '';
    this.clearAllFilters();
    
    // Navigate to search
    this.router.navigate(['/flightsearch']);
  }

  /**
   * Returns to search screen
   */
  returnToSearch(): void { 
    this.router.navigate(['/flightsearch']);
  }

  /**
   * Returns to booking screen (from payment screen)
   */
  returnToBooking(): void {
    this.currentView = 'booking';
    this.paymentStatus = 'pending';
    this.errorMessage = '';
  }

  /**
   * Returns to results screen (from booking screen)
   */
  returnToResults(): void {
    this.currentView = 'results';
  }
}